/*
- Overhauled the 3d sound system to account for walls
- Sound configuration options are now available in the sound_info table, defined in sound_info.lua
- Added support for localization (or easier modification) of text strings
- Added keep_viewmode option to the fullscreen renderer, which will draw the inventory view if the renderer is invoked from an inventory
- Added sys_get_border_eyemouth to tell the inventory renderer what borders to draw around the eye and mouth
- Added min_skill to spells to specify an absolute minimum skill level needed to cast the spell
- Added additional hooks to sys_cast_spell to make it less monolithic
- Doors can now be set to be clickable, just like upright flooritems
- Fixed subrenderer msgzones flickering on and off
- Fixed a situational crash when viewing the inventory screen
- Fixed a timing discrepancy between the attack cooldown timer and message timers
- Improved handling of msgzones on inventory screen, including fixing other assorted bugs
- Removed ESB support for floating point values in exvars, as they don't work in DSB (and probably never will)
- Default font now includes curly braces and the euro symbol (€)
- Dungeon Master "D" icon now shown while program is running
*/

/*
DSB 0.76 includes support for localization (or easier modification) of text strings; most of the text strings that were formerly more or less hardcoded are now found in [i]base/localtext.txt[/i].

If you want to modify these strings for your own dungeon, you can create your own copy of [i]localtext.txt[/i] in your dungeon's directory, containing your own text strings. You can also overwrite any of DSB's standard text strings.

The format of a [i]localtext.txt[/i] is a series of lines, each one consisting of a key (without whitespace), one or more tabs, and then a text string. In your code, use dsb_locstr(key) to grab an entry from your [i]localtxt.txt[/i].

Example:
The following is defined in DSB's [i]localtext.txt[/i]:
[code]
COINFLIP_HEADS		IT COMES UP HEADS.
[/code]

This text is output via the coin's attack method with this code:
[code]
dsb_write(system_color, dsb_locstr("COINFLIP_HEADS"))
[/code]
When the "FLIP" method is invoked, it prints the expected "IT COMES UP HEADS." when the coin comes up heads.

Attack methods themselves also have localization text. The key can be specified by the dungeon designer or auto-generated by DSB via the [b]auto_loc_key[/b] property. Methods without proper localized text are displayed using their name in the table (just like they were in 0.75 and before) so this shouldn't break any older dungeons.

You can also create additional localtext files with an underscore and an uppercase two-letter code for the purpose of localization, for example, [i]localtext_DE.txt[/i] for German text. If (and only if) the user's locale (in [i]dsb.ini[/i]) is set to DE, it will load this file. 
*/

// TODO: Better way to work on dsb data files
// TODO: Support for subtile monster movement(?)
// TODO: Load fonts with alpha channel support -- doesn't seem possible with current Allegro

// TODO: Problem with sys_ functions... some are good for overriding, others are bulky?

/*
TODO: Monsters can send a message on various events

TODO: Specify the delay for cumulative damage
TODO: Multiple enemy graphics possible without dsb_qswapping between archs
TODO: GUI stuff should respect transparency and alpha channels
TODO: Use DM icon sheet for ESB
TODO: Food/water goes down too fast maybe? (check with CSBwin code)

TODO: Support alpha masks on doors with decorations and such things
TODO: Wall window compo that supports alpha
TODO: Eventually remove all requirements to use 256 color icons/graphics
TODO: Get rid of FTL font in file requests
TODO: User bindable keys (TAB for custom GUI button)
TODO: Change size of inventory subrenderers (fix res/rei to make this easier)
TODO: Be able to move champions ppos around
TODO: Sound volume control

TODO: Add optional parameter to dsb_viewport_distort to better control the distortion
TODO: Expand the usefulness of setup_icons(gfx_table_entry, bitmap)
TODO: Maybe integrate gameloop into fullscreen renderer so game can tick
TODO: Ambient light arch based solely on radius
TODO: Specify "transparent?" for monsters
TODO: Add a creature naming scroll to the standard archetypes
TODO: Add flag to allow monsters to move through walls and be drawn
TODO: Recolorable graphics with alpha channels -- or something like that to use pixel-level tinting
TODO: Control over height of flying objects
TODO: Add alternate front view to wallset_ext
TODO: Set "default" attack method that you can get by right clicking


*/

/*
ESB todo:
metaobjects/wizards?
graphics assistant?
*/
